### PR TITLE
Added `entity.name.function` and `entity.name.type` selectors

### PR DESCRIPTION
**Pull request by Hibou57**
See comment for YAML source file commit.

### CODE REVIEW

**Comment by Hibou57** [comment]
Note in a third commit, I also reordered the repository entries alphabetically, which may looks like a lot of change, but only the first commit to the YAML source file is the change to really care about.

**Comment by Hibou57** [comment]
Finally added an `entity.name.type` selector too.

**Comment by steinwaywhw** [comment]
Hi, thanks a lot. I really appreciate it. Give me a couple of days to double check and then I will merge.

**Comment by steinwaywhw** [comment]
Thanks, that's a lot of hard work!

**Comment by Hibou57** [comment]
Thanks for your thanks… I was afraid to annoy with too much commit.

If you don't mind, I will have some check again later. For the story, I started to write my own tmLanguage before I discovered yours. I did mine looking at ATS sources to be sure the rules are correct. As I will be using your package, I will check your tmLanguage conforms to what ATS2 sources says.

There are many things I would like, but I'm aware it's not possible to be perfect with regex, which is not like really parsing.

**Comment by steinwaywhw** [comment]
No problem. It's just I'm busy dealing with something else at the moment and I feel like delaying a response to you would cause trouble. More checking is definitely needed. My thought is that, try to make it good enough for daily use and that's it. It's impossible to make it perfect only by using regex since it is far beyond regular language.

**Comment by Hibou57** [comment]
Hello,

Trying to making good enough for daily use, is indeed what I do. I'm fixing as I see needs when editing ATS source. For the checking, I will add a Markdown file with the process used explicitly explained. Don't worry if you're busy, especially if that's for good things :-P . I will commit in my branch and wait some time for the next pull request anyway.

See you soon and have a good time as much as possible.

**Pull request merged**
